services:
  server:
    container_name: secuscan-back
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/
      MONGO_DBNAME: secuscan
    env_file:
      - ".env"

  frontend:
    container_name: secuscan-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      API_URL: server
    ports:
      - 5173:5173
    env_file:
      - ".env"

  gh-server:
    container_name: auth-server
    build:
      context: ./frontend
      dockerfile: auth.Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ".env"

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
      MONGO_INITDB_DATABASE: secuscan
