services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      env_file: .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      API_URL: server
    ports:
      - 3000:3000
