services:
  server:
    container_name: secuscan-back
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ".env"

  frontend:
    container_name: secuscan-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      API_URL: server
    ports:
      - "5173:5173"
    env_file:
      - ".env"

  gh-server:
    container_name: auth-server
    build:
      context: ./frontend
      dockerfile: auth.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ".env"
